spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/racf/springboot-service-config-server
            
server:
  port: 8888
  

